In [0]:
#os.chdir("C:/Users/Admin/Desktop")
data=pd.read_csv("weather_dataset.csv")

In [0]:
data.columns
len(data)

51315

In [0]:
data["dt"][1]-data["dt"][2]

-3600

In [0]:
c=0
l=[]

731


In [0]:
l1=data["dt"]

In [0]:

print(mylist)

[1349096400, 1349100000, 1349103600, 1349107200, 1349110800, 1349114400, 1349118000, 1349121600, 1349125200, 1349128800, 1349132400, 1349136000, 1349139600, 1349143200, 1349146800, 1349150400, 1349154000, 1349157600, 1349161200, 1349164800, 1349168400, 1349172000, 1349175600, 1349179200, 1349182800, 1349186400, 1349190000, 1349193600, 1349197200, 1349200800, 1349204400, 1349208000, 1349211600, 1349215200, 1349218800, 1349222400, 1349226000, 1349229600, 1349233200, 1349236800, 1349240400, 1349244000, 1349247600, 1349251200, 1349254800, 1349258400, 1349262000, 1349265600, 1349269200, 1349272800, 1349276400, 1349280000, 1349283600, 1349287200, 1349290800, 1349294400, 1349298000, 1349301600, 1349305200, 1349308800, 1349312400, 1349316000, 1349319600, 1349323200, 1349326800, 1349330400, 1349334000, 1349337600, 1349341200, 1349344800, 1349348400, 1349352000, 1349355600, 1349359200, 1349362800, 1349366400, 1349370000, 1349373600, 1349377200, 1349380800, 1349384400, 1349388000, 1349391600, 134

In [0]:
for i in range(len(mylist)-1):
  if mylist[i]-mylist[i+1]==0:
    l.append(c)
    print(c)
    c=0
    break
  c=c+1

In [0]:
df=data.drop_duplicates(subset="dt",keep="last")

In [0]:
len(df)

51169

In [0]:
lastvl=data["dt"][51169]
lastvl

1532779200

In [0]:
test=[]

In [0]:
day=int(input("Enter The number of days you need to predict"))

Enter The number of days you need to predict31


In [0]:
for i in range(24*day):
  test.append(lastvl+(3600*i))

In [0]:
for i in range(len(test)-1):
  print(test[i]-test[i+1])

-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-3600
-360

In [0]:
#X_test=data["dt"][40000:]

In [0]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [0]:
regressor=LinearRegression()

In [0]:
df=pd.DataFrame()

In [0]:
df["dt"]=data["dt"][:40001]
df["temp"]=data["temp"][:40001]

In [0]:
X=np.array(df["dt"])
X=X.reshape(1,-1)
X=X.reshape(-1,1)

X

array([[1349096400],
       [1349100000],
       [1349103600],
       ...,
       [1492621200],
       [1492624800],
       [1492628400]])

In [0]:
from sklearn import preprocessing
standardized_X = preprocessing.scale(X)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:172: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [0]:
regressor.fit(standardized_X,df["temp"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
X_test=np.array(data["dt"][40001:])
X_test=X_test.reshape(1,-1)
X_test=X_test.reshape(-1,1)
X_test

array([[1492632000],
       [1492635600],
       [1492639200],
       ...,
       [1533294000],
       [1533297600],
       [1533301200]])

In [0]:
import math
from sklearn import metrics

In [0]:
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

standardized_X = preprocessing.scale(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:172: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [0]:
y_predicted = regressor.predict(standardized_X)


In [0]:
rmse = math.sqrt(mean_squared_error(data["temp"][40001:], y_predicted))
r2 = r2_score(data["temp"][40001:], y_predicted)

In [0]:
print(np.sqrt(metrics.mean_squared_error(data["temp"][40001:], y_predicted)))

3.924627943912974


In [0]:
print(min(data["temp"]),max(data["temp"]))

0.0 314.1


In [0]:
out=pd.DataFrame()
out["real"]=data["temp"][40001:]
out["predicted"]=y_predicted
out.to_csv("linear_regression.csv")

In [0]:
import matplotlib.pyplot as plt
plt.plot(data["temp"][40001:], color = 'red', label = 'Real Company Prices')
plt.plot(y_predicted, color = 'blue', label = 'Predicted company Price')
plt.title('Stock Price Prediction')
plt.xlabel('Time')
plt.ylabel('Stock Price')
plt.legend()
plt.show()


In [0]:
# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('/content/drive')

In [0]:
plt.savefig('testplot.png')

In [0]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import StandardScaler # Used for scaling of data
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras import metrics
from sklearn import preprocessing
import seaborn as sns
import matplotlib.pyplot as plt
from keras import backend as K
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt


In [0]:
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(30, input_dim=standardized_X.shape[1], activation='relu'))
    model.add(Dense(90, activation='relu'))
    model.add(Dense(90, activation='relu'))
    model.add(Dense(90, activation='relu'))
    model.add(Dense(1))
    # Compile model
    model.compile(optimizer ='adam', loss = 'mean_squared_error', 
              metrics =[metrics.mae])
    return model

model = create_model()
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 30)                60        
_________________________________________________________________
dense_7 (Dense)              (None, 90)                2790      
_________________________________________________________________
dense_8 (Dense)              (None, 90)                8190      
_________________________________________________________________
dense_9 (Dense)              (None, 90)                8190      
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 91        
Total params: 19,321
Trainable params: 19,321
Non-trainable params: 0
_________________________________________________________________


In [0]:
df["temp"]

0        298.00
1        298.00
2        298.00
3        298.00
4        298.00
5        298.00
6        298.00
7        298.00
8        298.00
9        298.00
10       298.00
11       298.00
12       298.00
13       298.00
14       298.00
15       298.00
16       298.00
17       298.00
18       298.00
19       298.00
20       298.00
21       298.00
22       298.00
23       298.00
24       298.00
25       298.00
26       298.00
27       298.00
28       298.00
29       296.00
          ...  
39971    304.15
39972    303.15
39973    302.15
39974    302.15
39975    301.15
39976    301.15
39977    300.15
39978    300.15
39979    299.15
39980    299.15
39981    299.15
39982    299.15
39983    299.15
39984    300.15
39985    300.15
39986    302.15
39987    305.15
39988    306.15
39989    308.15
39990    309.15
39991    309.15
39992    309.15
39993    307.15
39994    306.15
39995    305.15
39996    303.15
39997    302.15
39998    301.15
39999    301.15
40000    300.15
Name: temp, Length: 4000

In [0]:
history = model.fit(standardized_X, df["temp"], epochs=200, batch_size=32)


Epoch 1/200
40001/40001 [==============================] - 2s 58us/step - loss: 4589.4163 - mean_absolute_error: 25.4815
Epoch 2/200
40001/40001 [==============================] - 2s 43us/step - loss: 25.0624 - mean_absolute_error: 3.5614
Epoch 3/200
40001/40001 [==============================] - 2s 43us/step - loss: 25.6854 - mean_absolute_error: 3.6138
Epoch 4/200
40001/40001 [==============================] - 2s 43us/step - loss: 26.3197 - mean_absolute_error: 3.6608
Epoch 5/200
40001/40001 [==============================] - 2s 43us/step - loss: 26.5682 - mean_absolute_error: 3.6842
Epoch 6/200
40001/40001 [==============================] - 2s 43us/step - loss: 26.2895 - mean_absolute_error: 3.6732
Epoch 7/200
40001/40001 [==============================] - 2s 43us/step - loss: 26.5934 - mean_absolute_error: 3.6904
Epoch 8/200
40001/40001 [==============================] - 2s 43us/step - loss: 26.0262 - mean_absolute_error: 3.6513
Epoch 9/200
40001/40001 [============================

In [0]:
X_test=np.array(data["dt"][40001:])
X_test=X_test.reshape(1,-1)
X_test=X_test.reshape(-1,1)
X_test
standardized_X = preprocessing.scale(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:172: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [0]:
import pickle
path= "model.pkl"
with open(path, 'wb') as f:
        pickle.dump(model, f)
        print("Done Pickiling")

Done Pickiling


In [0]:

from pandas import DataFrame
import pickle
from sklearn import linear_model
import statsmodels.api as sm
with open("./model.pkl", 'rb') as f:
            model = pickle.load(f)

Using TensorFlow backend.
W0705 10:19:46.130363 140381121509248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0705 10:19:46.177039 140381121509248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0705 10:19:46.260375 140381121509248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0705 10:19:46.261695 140381121509248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0705 10:19:46.26

In [0]:
X_test

array([[1492632000],
       [1492635600],
       [1492639200],
       ...,
       [1533294000],
       [1533297600],
       [1533301200]])

In [0]:

prediction= model.predict(X_test)

array([[7.5496006e+10],
       [7.5496194e+10],
       [7.5496374e+10],
       ...,
       [7.7552648e+10],
       [7.7552845e+10],
       [7.7553025e+10]], dtype=float32)

In [0]:
from sklearn.metrics import confusion_matrix

rmse = sqrt(mean_squared_error(data["temp"][40001:], prediction))


model.summary()

rmse

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 30)                60        
_________________________________________________________________
dense_7 (Dense)              (None, 90)                2790      
_________________________________________________________________
dense_8 (Dense)              (None, 90)                8190      
_________________________________________________________________
dense_9 (Dense)              (None, 90)                8190      
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 91        
Total params: 19,321
Trainable params: 19,321
Non-trainable params: 0
_________________________________________________________________


51825627008.51317

In [0]:
l2=data["temp"][40001:]

In [0]:
# summarize history for accuracy
plt.plot(l2)
plt.plot(prediction)
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['test original', 'prediction'], loc='upper left')
plt.show()
# summarize 

In [0]:
plt.savefig('testplot.png')

In [0]:
print(len(l2),len(prediction))

11314 11314


In [0]:
out=pd.DataFrame()
out["real"]=l2
out["predicted"]=prediction
out.to_csv("linear_regression.csv")